Don't calculate slots when MRO parsing fails.
PyCQA/astroid pull request #1089
Opened 2021-07-07 10:25 UTC by doranid

## Steps

- [x] For new features or bug fixes, add a ChangeLog entry describing what your PR does.
- [x] Write a good description on what the PR does.

## Description

`slots()` won't now fail if it can't parse the mro object.
I'm not sure that's the right way to fix that.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Related Issue

#1088 

Thanks!

2021-07-09 19:18 UTC, Pierre-Sassoulas commented
Probably the astroid fix we need for https://github.com/PyCQA/pylint/pull/4688, thank you !

2021-07-09 19:40 UTC, doranid commented
> Probably the astroid fix we need for [PyCQA/pylint#4688](https://github.com/PyCQA/pylint/pull/4688), thank you !

These two issues are orthogonal as per my understanding.

Thanks!

2021-07-09 20:14 UTC, Pierre-Sassoulas requested changes
I don't know how I would test that, but would it be possible to add an automated test for this change ?

2021-07-09 20:14 UTC, Pierre-Sassoulas commented on astroid/scoped_nodes.py
> +        def grouped_slots(mro):
```suggestion
        def grouped_slots(mro: ?) -> None:
```
Could you add typing on modified functions, please ? :)

2021-07-10 18:27 UTC, Pierre-Sassoulas approved these changes
Thank for adding a test, I'm going to wait for another reviewer before merging :)

2021-08-01 19:04 UTC, merged