Add dependency on setuptools
PyCQA/astroid pull request #1100
Opened 2021-07-16 17:40 UTC by NeilGirdhar

Without the dependency on setuptools, poetry won't update setuptools when updating astroid.  And if a user uninstalls setuptools, poetry won't reinstall it when updating.  This causes the cryptic error "'pkg_resources' has no attribute '_namespace_packages' " when running pylint.

2021-07-18 07:03 UTC, Pierre-Sassoulas commented
Are you on the latest astroid ? We used ``scm_setuptools`` in very recent version but we removed it in #1030 If we still need setuptools after 1030, I'd rather do what's necessary to not depend on it.

2021-07-18 13:30 UTC, NeilGirdhar commented
@Pierre-Sassoulas I am on the latest.  The trouble is this line in `astroid/interpreter/_import/util.py`:
```python
return pkg_resources is not None and modname in pkg_resources._namespace_packages
```
I believe you can't access that without `setuptools`.

2021-07-18 16:48 UTC, Pierre-Sassoulas commented
The code should not fail though, it's guarded by a try catch:

```python
try:
    import pkg_resources
except ImportError:
    pkg_resources = None


def is_namespace(modname):
    return pkg_resources is not None and modname in pkg_resources._namespace_packages
```
I don't know how it's possible that you had an error. Did you do something particular to get the error ? It also look like ``distutils`` is used in a lot of place, (too much to refactor easily), maybe that's what should be added (it's included in setuptools, I guess)

2021-07-18 17:49 UTC, NeilGirdhar commented
But that line doesn't guard against the missing `setuptools`?

Right now, I can't reproduce the error I got though.  What I remember is that pylint was failing with that cryptic error, and then I installed setuptools and the error went away.  I wish I could reproduce it.

2021-07-18 18:06 UTC, Pierre-Sassoulas commented
It's possible that it's worse than just a dependency to setuptools and that we're depending on a specific version of setuptools (``pkg_resources._namespace_packages`` is private, so...). If we have the wrong version (the out-dated default version of the system ?) ``pkg_resources`` is not None and we get the error. To be frank I don't know what is the purpose of this code, I'd like to remove it if possible but this seems like a big retro-engineering and refactor (because of the distutils dependency).

2021-07-18 18:09 UTC, NeilGirdhar commented
> It's possible that it's worse than just a dependency to setuptools and that we're depending on a specific version of setuptools (pkg_resources._namespace_packages is private, so...).

I actually tested this, and found that you fail with setuptools version 10, but it's mainly because setuptools 10 doesn't seem to work at all.  Not sure what to do about that.

>  To be frank I don't know what is the purpose of this code, I'd like to remove it if possible but this seems like a big retro-engineering and refactor (because of the distutils dependency).

Yes, that would be awesome if it's possible.

2021-07-19 16:40 UTC, NeilGirdhar commented
Maybe you could just add another guard?
```python
return pkg_resources is not None and and hasattr(pkg_resources, '_namespace_packages') and modname in pkg_resources._namespace_packages
```

2021-07-19 17:05 UTC, Pierre-Sassoulas commented
Yeah you're  right, let's do the fast fix and open another issue for the refactor. Do you want to add this to your MR ?

2021-07-19 17:13 UTC, NeilGirdhar commented
Okay I'll do that

2021-07-19 18:33 UTC, NeilGirdhar commented
Done

2021-07-19 18:36 UTC, Pierre-Sassoulas requested changes
Thank for the fix. I think we might still need to add setuptools to the requirements (because of distutils used elsewhere) and you should add yourself to the contributor. Maybe  you could rebase this on your original changes if you still have the commit name ?

2021-07-19 18:38 UTC, NeilGirdhar commented
I overwrote it.  It's just one extra line in your requirements, right?  And I'll happily add my name to contributors.

2021-07-19 18:48 UTC, NeilGirdhar commented
Done, except I couldn't find the contributors list ?

2021-07-19 18:57 UTC, Pierre-Sassoulas approved these changes
Ho nevermind for the contributors I'm confusing astroid with pylint where there is a Contributors.txt. git is tracking all this anyway :)

2021-07-19 18:58 UTC, merged