Fix ``relative-beyond-top-level`` false positive
PyCQA/astroid pull request #1186
Opened 2021-09-21 13:10 UTC by DanielNoord

## Steps

- [ ] For new features or bug fixes, add a ChangeLog entry describing what your PR does.
- [x] Write a good description on what the PR does.

## Description

I believe this solves the false positive as discussed in the `pylint` issue. However, I'm not 100% comfortable with namespace packages so please tell me if I did anything wrong here.

I have not added a test yet, but I have openend a `pylint` PR which includes a test that does pass.
See: https://github.com/PyCQA/pylint/pull/5059

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Related Issue

https://github.com/PyCQA/pylint/issues/2967

2021-09-25 11:32 UTC, Pierre-Sassoulas requested changes
I think we need to add a test in astroid too. Maybe we can use the same one than in pylint ?

2021-09-26 18:06 UTC, DanielNoord commented
@Pierre-Sassoulas Would you mind taking a look at this? I have added the necessary files to create the same test as in `pylint` but I don't really understand how the unit tests with data work in `astroid`.

2021-09-26 20:53 UTC, Pierre-Sassoulas commented
> I don't really understand how the unit tests with data work in astroid.

There's no handy automated functional tests like in pylint :)  I think you have to parse them manually, there's probably example of reasing data in the testdata directory Maybe we could imagine adding some helper like in pylint but we'd have to create a text representation of the expected AST (?) This would be helpful but probably quite a lot of work too.

2021-09-26 20:56 UTC, DanielNoord commented
I used a unittest in `pylint` as well, but it was much easier to understand how I could load extra data.
Searching for some of the directories I found in `testdata` I did not find any hits within the tests. So I couldn't find any examples I could copy.

2021-09-26 21:07 UTC, Pierre-Sassoulas commented
@hippo91 how do you handle test using real file in ``testdata`` generally ?

2021-09-27 10:56 UTC, hippo91 commented
@Pierre-Sassoulas @DanielNoord i never had to use `testdata`. However it seems that one way is to use the `resources` module. 
I have to look a bit deeper to have an idea of how to use it for this specific PR.

2021-09-29 21:15 UTC, DanielNoord commented
Sorry for the rebase. I have added a test based on some of the others I saw using the `resources` module.

2021-10-05 11:40 UTC, Pierre-Sassoulas approved these changes

2021-10-05 11:40 UTC, merged

2021-10-05 21:00 UTC, cdce8p commented
This PR sees to cause a regression with the `too-many-function-args` warning for Home Assistant.
I'll need some more time to isolate the issue before posting code to reproduce it.

2021-10-05 22:02 UTC, cdce8p commented
Opened #1200 with an example to reproduce the error.