Make ``Module`` call the ``__init__`` of ``NodeNG``
PyCQA/astroid pull request #1262
Opened 2021-11-19 16:46 UTC by DanielNoord

## Steps

- [x] For new features or bug fixes, add a ChangeLog entry describing what your PR does.
- [x] Write a good description on what the PR does.

## Description

Found this while working on the `end_col_offset` issues.

@cdce8p Do you know why we don't do this? Without this `col_offset` isn't defined on `nodes.Module`. We could also define it in the `__init__` of `nodes.Module`, but this seem elegant as well?

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Related Issue

2021-11-19 16:52 UTC, DanielNoord commented
I guess I know why know: it will set `node.lineno` to `None` and we make many unguarded calls to `node.lineno` in `pylint`. We tend to do `int() + node.lineno` which shouldn't be allowed if we know that `node.lineno` can be `None`.

Problem for the future! Sorry for pinging!

2021-11-19 17:15 UTC, cdce8p reviewed
> Do you know why we don't do this?

Unfortunately not.

> Without this `col_offset` isn't defined on `nodes.Module`.

Haven't though about this tbh, but you're right. It should be defined even if `None`. That's what all other nodes without `lineno` and `col_offset` do too: https://github.com/PyCQA/astroid/commit/40d556070fd566b7bb43cb3ed0e498045b88f2d0

2021-11-19 17:15 UTC, cdce8p commented on astroid/nodes/scoped_nodes.py
> +        super().__init__(lineno=None, col_offset=None, parent=parent)
```suggestion
        super().__init__(parent=parent)
```
That is enough

2021-11-22 13:15 UTC, cdce8p commented on astroid/nodes/scoped_nodes.py
> +        super().__init__(parent=parent)
```suggestion
        super().__init__(lineno=1, parent=parent)
```
Mentioned it here: https://github.com/PyCQA/astroid/issues/1273#issuecomment-975510511. Let's try if that works.

2021-11-22 13:26 UTC, cdce8p commented on astroid/nodes/scoped_nodes.py
> +        super().__init__(lineno=1, parent=parent)
```suggestion
        super().__init__(lineno=0, parent=parent)
```
Seems like the `lineno` needs to be `0`.

2021-11-22 15:23 UTC, DanielNoord commented on tests/unittest_nodes_lineno.py
> +        """Test end_lineno and end_col_offset for Module"""
```suggestion
        """Tests for Module"""
```

2021-11-22 15:27 UTC, DanielNoord commented on tests/unittest_nodes_lineno.py
> +        assert module.lineno == 1
```suggestion
        assert module.lineno == 0
```

2021-12-15 14:14 UTC, Pierre-Sassoulas approved these changes
LGTM, do you want another review @DanielNoord ?

2021-12-15 14:16 UTC, DanielNoord commented
Let's wait for @cdce8p. He reported the initial issue that prompted this PR.

2021-12-15 23:26 UTC, cdce8p requested changes
Just some small comments, looks good otherwise.

2021-12-15 23:26 UTC, cdce8p commented on astroid/nodes/scoped_nodes.py
> +    lineno: Literal["0"] = 0
```suggestion
    lineno: Literal[0] = 0
```

2021-12-16 11:15 UTC, cdce8p approved these changes

2021-12-16 11:16 UTC, merged