Temporarily disable distutils test
PyCQA/astroid pull request #1316
Opened 2021-12-27 22:35 UTC by cdce8p

With v60.0.0 setuptools started monkeypatching the distuils module
to use their own vendored version. Longterm any uses of distuils
should be replaced or removed.

https://github.com/pypa/setuptools/pull/2896

--
This change isn't ideal as it might hide an underling error, but for now it will unblock the CI pipeline.

Closes #1313

References:
* #1282
* #1103

2021-12-28 06:49 UTC, Pierre-Sassoulas requested changes
We're trying to test ``find_spec`` in this test, distutils was used because it was supposed to be always present i guess. We might as well use another dependency we'll keep, like ``wrapt``, ``lazy_object_proxy`` (or ``setuptools``, but it might become problematic when we adopt pyproject.toml and something else than setuptools or if we dump setuptools.).

2021-12-28 13:16 UTC, DanielNoord commented
I think changing the package used for this test makes sense!

2021-12-29 19:28 UTC, cdce8p commented on tests/unittest_modutils.py
> +        self.assertEqual(found_spec.location, wrapt.decorators.__file__)
The test was specifically designed to test the location of `distutils`. So this change wouldn't fix it

2021-12-29 19:28 UTC, DanielNoord commented
I retract my earlier statement, see https://github.com/PyCQA/astroid/pull/672/files.

We actually want to test `distutils` here, the test was added specifically for it.

2021-12-29 19:31 UTC, cdce8p commented
The idea behind this PR was to **temporarily** disable the test just until we fix / resolve #1103 and #1282. It doesn't look like it's causing any real world issue at the moment, so we might get away with it.

2021-12-29 19:43 UTC, Pierre-Sassoulas commented
Seeing the issue in https://github.com/PyCQA/pylint/issues/73 the result could be false positive for distutil in pylint ?

2021-12-29 20:21 UTC, Pierre-Sassoulas approved these changes
I think this is a good temporary solution even if we regress on pylint #73 as distutil is old and deprecated.

2021-12-29 20:53 UTC, DanielNoord commented
I think I might have found a fix. I'll create a new PR.

2021-12-29 21:08 UTC, DanielNoord commented
See #1321. I think we can close this in favour of that one, test seem to be passing there 😄

2021-12-29 21:49 UTC, Pierre-Sassoulas commented
Amazing fix @DanielNoord !

2021-12-29 21:49 UTC, closed without merging