Fix builtin inference on property not including function arguments
PyCQA/astroid pull request #1366
Opened 2022-01-20 19:30 UTC by areveny

## Steps

- [X] For new features or bug fixes, add a ChangeLog entry describing what your PR does.
- [X] Write a good description on what the PR does.

## Description

This ensures that when we transform a call to the builtin `property` into an `objects.Property`, we correctly postinitialize its function arguments.

Not doing so leads to a crash in https://github.com/PyCQA/pylint/pull/5610. 

This PR can be merged, but testing it is dependent on #1365 because this code is not being called consistently so we can't write a test for it.

But sometimes the code is called, which is why it is needed for the Pylint issue above.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Related Issue

2022-01-20 20:06 UTC, Pierre-Sassoulas approved these changes
Great !

2022-01-20 20:08 UTC, DanielNoord requested changes

2022-01-20 20:08 UTC, DanielNoord commented on ChangeLog
> +* Fixed builtin inferenence on `property` calls not including function arguments
```suggestion
* Fixed builtin inferenence on `property` calls not calling the `postinit` of the new node, which
   resulted in instance arguments missing on these nodes.
```

2022-01-20 23:24 UTC, areveny commented
Added a unit test to validate postinit on the inferred `Property` by checking that the `args` attribute that is giving us trouble is initialized.

2022-01-20 23:54 UTC, DanielNoord commented on tests/testdata/python3/data/logging/__init__.py
> +# Copyright 2001-2019 by Vinay Sajip. All Rights Reserved.
Should this be in here?

2022-01-20 23:55 UTC, DanielNoord approved these changes
Looks good, besides the file that I think was added by mistake.

Thanks @areveny!

2022-01-21 00:16 UTC, merged

2022-01-21 00:24 UTC, areveny commented
Ah, dang. I merged without squashing. I'll check that it is squashed next time.