Fix typing and ``postinit`` in ``build_class``
PyCQA/astroid pull request #1452
Opened 2022-03-07 22:49 UTC by DanielNoord

## Steps

- [x] Write a good description on what the PR does.

## Description

Follow up to #1433.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |

## Related Issue

2022-03-07 23:29 UTC, cdce8p requested changes

2022-03-07 23:29 UTC, cdce8p commented on astroid/raw_building.py
> +    name: str, basenames: Sequence[str] = (), doc: Optional[str] = None
```suggestion
    name: str, basenames: Iterable[str] = (), doc: Optional[str] = None
```
If you start that way, we should use the least limiting base class. 😉

2022-03-07 23:29 UTC, cdce8p commented on astroid/raw_building.py
> +        bases=basenodes,
```suggestion
        bases=[nodes.Name(name=base, parent=node) for base in basenames],
```

2022-03-07 23:29 UTC, cdce8p commented on astroid/raw_building.py
> +        basenodes.append(basenode)
```suggestion
```

2022-03-07 23:29 UTC, cdce8p commented on astroid/raw_building.py
> +from typing import List, Optional, Sequence
```suggestion
from typing import Iterable, List, Optional
```

2022-03-08 08:27 UTC, Pierre-Sassoulas approved these changes
👍

2022-03-08 10:00 UTC, cdce8p approved these changes

2022-03-08 10:12 UTC, merged