Infer returned value of .copy() method for collections
PyCQA/astroid pull request #1540
Opened 2022-05-03 20:33 UTC by timmartin

## Description

Where Astroid can infer that the subject of a `.copy()` method call is a built-in type that supports the copy operator, we can infer that the returned value will have the same value as whatever was inferred.

This change only adds support for `list`, `dict`, `set` and `frozenset`; in theory we can apply it to anything inferred to be of type `collections.abc.MutableSequence`, but: a) that doesn't cover `set` and `frozenset` so we'd need special cases for them anyway and b) Astroid doesn't currently seem to support inferring which types implement `MutableSequence`.

`bytearray` is another type for which we could infer `.copy()` behavior, but Astroid doesn't seem to have any explicit support for it, so adding this looks like more work.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Related Issue

Closes #1403

2022-05-03 20:36 UTC, Pierre-Sassoulas commented on astroid/brain/brain_builtin_inference.py
> +    )
```suggestion
    return isinstance(node, (nodes.Dict, nodes.List, nodes.Set, objects.FrozenSet))
```
I think this work https://docs.python.org/3/library/functions.html#isinstance

2022-05-03 20:39 UTC, DanielNoord requested changes
Thanks for working on this! Just some nitpicks about typing and the `isinstance` calls. Test seem good!

2022-05-03 20:39 UTC, DanielNoord commented on astroid/brain/brain_builtin_inference.py
> +def _looks_like_copy_method(node):
```suggestion
def _looks_like_copy_method(node: nodes.Call) -> bool:
```

2022-05-03 20:39 UTC, DanielNoord commented on astroid/brain/brain_builtin_inference.py
> +def _has_copy_method(node):
```suggestion
def _has_copy_method(node: nodes.NodeNG) -> bool:
```

2022-05-03 20:39 UTC, DanielNoord commented on astroid/brain/brain_builtin_inference.py
> +    )
```suggestion
    return isinstance(node, (nodes.Dict, nodes.List, nodes.Set, objects.FrozenSet))
```

2022-05-03 20:39 UTC, DanielNoord commented on astroid/brain/brain_builtin_inference.py
> +def _infer_copy_method(node, context=None):
```suggestion
def _infer_copy_method(node: nodes.Call, context: Optional[InferenceContext]=None) -> ...:
```

I think the return value is `Iterator[Union[nodes.Dict, nodes.List, nodes.Set, objects.FrozenSet]]`?

2022-05-03 22:10 UTC, cdce8p requested changes

2022-05-03 22:10 UTC, cdce8p commented on astroid/brain/brain_builtin_inference.py
> +    inferred = list(node.func.expr.infer(context=context))
With `list` you evaluate the whole iterator even if the condition would later exit early. The work is done. [itertools.tee()](https://docs.python.org/3/library/itertools.html#itertools.tee) should work here.

2022-05-03 22:10 UTC, cdce8p commented on astroid/brain/brain_builtin_inference.py
> +    if all(_has_copy_method(x) for x in inferred):
With the suggestions `_has_copy_method` is a single `isinstance` call. We could safe multiple function lookups / calls if we just inline it here.

2022-05-03 22:10 UTC, cdce8p commented on tests/unittest_inference.py
> +        b #@
I would suggest to choose different variable names for each case. That could make debugging a bit easier if something were to go wrong at some point.

Could you also add a case for which we **can't** infer `copy()`?

2022-05-03 22:10 UTC, cdce8p commented on ChangeLog
> +* Infer the return value of the ``.copy()`` method on ``dict``, ``list``, ``set``
```suggestion
* Infer the return value of the ``.copy()`` method on ``dict``, ``list``, ``set``,
```

2022-05-08 20:55 UTC, cdce8p reviewed
The changes look great! Just some last comments, then it's ready.

2022-05-08 20:55 UTC, cdce8p commented on astroid/brain/brain_builtin_inference.py
> +) -> Iterator[Union[nodes.Dict, nodes.List, nodes.Set, objects.FrozenSet]]:
```suggestion
) -> Iterator[nodes.NodeNG]:
```
The result is only use the check the function itself, nothing else. So it's not necessary to constrict it too much.

2022-05-08 20:55 UTC, cdce8p commented on astroid/brain/brain_builtin_inference.py
> +from typing import Iterator, Optional, Union
```suggestion
from typing import Iterator, Optional
```

2022-05-08 20:55 UTC, cdce8p commented on astroid/brain/brain_builtin_inference.py
> +    inferred_orig, inferred_copy = itertools.tee(node.func.expr.infer(context=context))
```suggestion
    assert isinstance(node.func, nodes.Attribute)
    inferred_orig, inferred_copy = itertools.tee(node.func.expr.infer(context=context))
```
This is already checked in `register_transform` but mypy doesn't know about it.

2022-05-10 19:54 UTC, cdce8p commented on astroid/brain/brain_builtin_inference.py
> +) -> Iterator[nodes.nodeNG]:
```suggestion
) -> Iterator[nodes.NodeNG]:
```

2022-05-10 20:05 UTC, cdce8p approved these changes
Looks good now! Thanks @timmartin 🚀

2022-05-10 20:05 UTC, merged