Fixes #1717 - ignore FutureWarnings which are raised by pandas
PyCQA/astroid pull request #1719
Opened 2022-07-19 21:09 UTC by timkpaine

Long description and repro in https://github.com/PyCQA/astroid/issues/1717

## Steps

- [x] For new features or bug fixes, add a ChangeLog entry describing what your PR does.
- [x] Write a good description on what the PR does.

## Description

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Related Issue

https://github.com/PyCQA/astroid/issues/1717

2022-07-19 22:24 UTC, jacobtylerwalls reviewed
Thank you for submitting a patch!

I looked at the blame to find why we're even escalating warnings to errors in the first place. It looks like the author was somewhat uncertain and it escaped discussion during review, see #785. I would be in favor of just changing the warningsfilter to "ignore" instead of "error" and then removing the warning types from the `except`. Otherwise, we could be back here with `UserWarning` or anything else. What do you think?

2022-07-20 06:37 UTC, Pierre-Sassoulas reviewed
Thank you for opening the issue and fixing the problem yourself, much appreciated !

2022-07-20 06:37 UTC, Pierre-Sassoulas commented on astroid/raw_building.py
>                  continue
I agree with @jacobtylerwalls that we should (try to) change the filtering logic to not escalate to error (it's risky if we miss one escalation, on the top of my head we're missing UserWarning, PendingDeprecationWarning and SyntaxWarning at least).Maybe something like this ?
```python
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    member = getattr(obj, name)
```    

 I'm wondering what we do in  ``attach_dummy_node(node, name)`` that could necessitate to list everything. But I just checked and we indeed missed a lot of warning, it's actually surprising that this was not reported before : https://docs.python.org/3/library/warnings.html#warning-categories. Are those specific warnings never used in any library pylint astroid is parsing ?

2022-07-20 15:27 UTC, timkpaine commented
Another option is to just catch the base warning class, but I agree just ignoring it all is probably better and certainly cleaner.

2022-07-21 15:36 UTC, Pierre-Sassoulas approved these changes
👌

2022-07-23 13:33 UTC, jacobtylerwalls requested changes
Glad to have the fix in. I checked the regression test, and it [passes](https://github.com/jacobtylerwalls/astroid/pull/72) without your changes. Maybe a test that just uses `unittest.mock` to emit a `FutureWarning` as a side effect would be simpler?

This is a minor detail, but if you do end up needing to create a test module, perhaps you can put it with the others under `tests/testdata/python3/data`.

2022-07-23 15:58 UTC, timkpaine commented
@jacobtylerwalls I accidentally broke the test by adding `Float64Index=""` to the fake module, if you remove that it should fail. I've fixed that test and moved the module inside the data folder

2022-07-23 19:40 UTC, jacobtylerwalls approved these changes

2022-07-23 19:46 UTC, merged