Remove str instance in model of BaseException.attrs
PyCQA/astroid pull request #1722
Opened 2022-07-26 15:05 UTC by mymedia2

Do not require first exception argument to be a string. The word "usually" does not imply an obligation.
https://docs.python.org/3/library/exceptions.html#BaseException.args

## Steps

- [ ] For new features or bug fixes, add a ChangeLog entry describing what your PR does.
- [ ] Write a good description on what the PR does.

## Description

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Related Issue

Closes: PyCQA/pylint#7233

2022-07-27 08:15 UTC, Pierre-Sassoulas commented
All tests are still passing on pylint current main branch.

2022-07-27 08:26 UTC, Pierre-Sassoulas approved these changes
I created https://github.com/PyCQA/pylint/pull/7236 in pylint, it fails without this, it succeed with it, thank you for fixing the issue, 👍

2022-07-30 11:14 UTC, DanielNoord requested changes
I think it makes more sense to add the test in `astroid`, that's where the change is and also is a better place for a test in case we change this later on.

@mymedia2 Could you add a test similar to the one Pierre added in this PR please?

2022-07-30 11:14 UTC, DanielNoord commented on astroid/interpreter/objectmodel.py
>      def attr_args(self):
```suggestion
    def attr_args(self) -> nodes.Tuple:
```

2022-07-30 11:14 UTC, DanielNoord commented on astroid/interpreter/objectmodel.py
> +        return node_classes.Tuple(parent=self._instance)
```suggestion
        return nodes.Tuple(parent=self._instance)
```

2022-08-23 09:27 UTC, DanielNoord commented
Superseded by https://github.com/PyCQA/astroid/pull/1749

2022-08-23 09:27 UTC, closed without merging