Bump ``wrapt`` to ``1.14``
PyCQA/astroid pull request #1745
Opened 2022-08-21 11:24 UTC by DanielNoord

## Steps

- [x] For new features or bug fixes, add a ChangeLog entry describing what your PR does.
- [x] Write a good description on what the PR does.

## Description

Ref. https://github.com/PyCQA/astroid/issues/1516#issuecomment-1220984764.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Related Issue

2022-08-21 17:17 UTC, Pierre-Sassoulas reviewed
I think we should differentiate between Python 3.11 and other interpreters. We are compatible with wrap lower than 1.14 after all, let's not create dependency issues fort user if we can easily avoid them.

2022-08-21 17:54 UTC, DanielNoord commented
But `1.14` supports `3.5+`? Wouldn't we unnecessarily complicate our own dependency for gains that we do not know about?

2022-08-22 12:47 UTC, Pierre-Sassoulas commented
> But 1.14 supports 3.5+?

The issue is not the version of the interpreter but the version required by all the other libs that can be installed by someone wanting to use pylint. There's probably a dependency on pypi or in an internal pypi repository somewhere that ask for wrapt < 1.14 (maybe for good reason, maybe without good reason but...). pylint/astroid would be impossible to install alongside it.

2022-08-22 12:55 UTC, Pierre-Sassoulas requested changes
The diff looks bad, but I don't know what I did wrong.

2022-08-22 12:55 UTC, Pierre-Sassoulas commented on pyproject.toml
> +    "wrapt>=1.14,<2",
```suggestion
    "wrapt>=1.14,<2;python_version>='3.11'",
    "wrapt>=1.11,<2;python_version<'3.11'",
```

2022-08-22 14:08 UTC, DanielNoord commented on ChangeLog
> +* Bumped minimum requirement of ``wrapt`` to 1.14.
```suggestion
* Bumped minimum requirement of ``wrapt`` to 1.14 on Python 3.11.
```

2022-08-22 16:03 UTC, Pierre-Sassoulas approved these changes

2022-08-22 17:25 UTC, merged