Mandatory fields
PyCQA/astroid pull request #1891
Opened 2022-11-29 06:40 UTC by nickdrozd

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |

This is a fun one.

[This comment](https://github.com/PyCQA/astroid/pull/1885#discussion_r1030791292) got me to thinking about required fields. There are many places in the code where a field is assumed to be not none even though the field annotation gives it as optional. Mypy rightly complains about this.

There are three ways to deal with this: (1) not-none assertions (yikes), (2) instance checks (yuck), and (3) annotate the fields as mandatory. This PR attempts (3).

Running Mypy strict, this reduces warnings from **1534** to **1478**, which is pretty good. I'm assuming this also will improve performance slightly.

In many cases, making the fields mandatory means that they aren't set until `postinit`, and so there isn't anything node-specific to do in `__init__`. So the `__init__` method can be deleted altogether since it does nothing but delegate to `super`.

2022-11-29 17:02 UTC, DanielNoord commented
I think @cdce8p has some ideas about this, but at the same time his ideas might have changed now that we are planning for `3.0`. Let's discuss!

2022-12-20 14:01 UTC, nickdrozd commented
In non-strict mode, this change reduces Mypy errors from **364** to **313**. And that's just from the nodes that have been done so far.

Really, I think this is the only viable path forward. There are just too many type errors otherwise.

2023-02-01 19:44 UTC, nickdrozd commented
@cdce8p Any thoughts on this one?

2023-02-01 23:06 UTC, cdce8p requested changes
The idea is good, however in it's current for this will be a massive breaking change. As you might have seen, there is already some logic in place to deprecate certain default values but all in all that needs more time more and more consideration before I would move forward with it.

This is certainly something we can do in some form for `3.0`, but it isn't a priority for me at the moment.

I'll be quite busy the next few weeks. Maybe I have some time after that towards late March  - April.

--
Sorry to disappoint you again here. Adding type annotations is valuable, however there are also other considerations at play here. It isn't particularly easiest to work with such old legacy code. Sometimes is better to be careful.

2023-02-02 15:42 UTC, nickdrozd commented
Maybe there are use cases I don't understand. Suppose this change were merged and released immediately. Who would notice? What exactly would break?

2023-02-02 15:57 UTC, DanielNoord commented
> Maybe there are use cases I don't understand. Suppose this change were merged and released immediately. Who would notice? What exactly would break?

There are dependants on `astroid`. Such as https://github.com/readthedocs/sphinx-autoapi.
We can't remove stuff without giving them time to react or prepare.

_That said, I would highly be in favour of just taking `astroid` private, but that has other issues assosciated with it._

2023-02-02 16:11 UTC, Pierre-Sassoulas commented
Last month a quarter of a million unique astroid downloads were not directly linked to pylint (according to pypystats: this is the number of astroid download last month minus the number of pylint download last month). This does not account for one of astroid's use case in pre-commit hook where it's analyzing code and is downloaded by pre-commit and not via pip. So breaking astroid's API can potentially break a sizable number of small packages and bother numerous maintainers and users. We need to deprecate with a proper waiting period before removing. 

Which is not to mean that we should suffer until the end of time because of the current state of the codebase and not touch anything. But we do need to be responsible about it and let other maintainers adapt in a reasonable time.

2023-02-02 20:07 UTC, nickdrozd commented
I understand that there are non-Pylint users of Astroid. But that isn't my question. My question is: which of those users would be impacted by this change? Does anyone know of any specific examples of code that would break as a result of the changes in this PR?

Or to put it another way, are there any test cases that could be added that would break in the presence of this change?

2023-02-02 20:11 UTC, DanielNoord commented
That's not really how dependencies and semantic versioning work.. We simply don't know how users use the tool, just as we don't know how people use `pylint`. We make assumptions and try not to change anything in the public API, without deprecations.

For `astroid` we haven't defined what is public and what isn't, so therefore everything kind of is... That's annoying, but something we sort of have to deal with.

2023-02-23 20:43 UTC, closed without merging