Fix a false positive with user-defined `Enum` class
PyCQA/astroid pull request #1967
Opened 2023-01-14 14:05 UTC by mbyrnepr2

Refs PyCQA/pylint#5719

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |
| ✓   | :sparkles: New feature |
| ✓   | :hammer: Refactoring   |
| ✓   | :scroll: Docs          |

## Description

Refs #XXXX

Closes #XXXX

2023-01-14 14:08 UTC, DanielNoord requested changes

2023-01-14 14:08 UTC, DanielNoord commented on astroid/brain/brain_namedtuple_enum.py
> +ENUM_QNAME: Final = "enum.Enum"
```suggestion
ENUM_QNAME: Final[str] = "enum.Enum"
```

2023-01-14 14:08 UTC, DanielNoord commented on astroid/brain/brain_namedtuple_enum.py
> +from typing import Final
This needs a `sys` version check.

2023-01-14 14:08 UTC, DanielNoord commented on ChangeLog
> +* Fix a false positive when an attribute named ``Enum`` was confused with ``enum.Enum``.
This needs to be moved to `2.13.3`

2023-01-14 14:17 UTC, mbyrnepr2 commented on ChangeLog
> +
```suggestion
```

2023-01-14 16:37 UTC, DanielNoord requested changes
I like the test, very elegant!

Couple of nits, rest LGTM!

2023-01-14 16:37 UTC, DanielNoord commented on astroid/brain/brain_namedtuple_enum.py
> +TYPING_NAMEDTUPLE_BASENAMES = {"NamedTuple", "typing.NamedTuple"}
```suggestion
TYPING_NAMEDTUPLE_BASENAMES: Final[set[str]] = {"NamedTuple", "typing.NamedTuple"}
```

2023-01-14 16:37 UTC, DanielNoord commented on astroid/brain/brain_namedtuple_enum.py
> +
```suggestion
```

2023-01-14 16:37 UTC, DanielNoord commented on tests/unittest_brain.py
> +        """Test the user-defined class named `Enum` is not inferred as `enum.Enum`"""
```suggestion
        """Test that the user-defined class named `Enum` is not inferred as `enum.Enum`"""
```

2023-01-14 18:04 UTC, mbyrnepr2 commented
Thanks for those suggestions @DanielNoord; nothing I can disagree with there!

2023-01-14 18:57 UTC, Pierre-Sassoulas approved these changes

2023-01-15 10:58 UTC, DanielNoord approved these changes
I'd like to see coverage, but other than that this LGTM!

2023-01-15 14:01 UTC, DanielNoord commented
@mbyrnepr2 Do you think you can get the diff coverage to 100% here?

2023-01-15 17:18 UTC, DanielNoord approved these changes
Thanks for the additional test!

2023-01-15 17:26 UTC, merged

2023-01-17 21:37 UTC, DanielNoord commented
@mbyrnepr2 Could you try and backport this? For some reason `git` doesn't recognize the `maintenance` branch for me locally.

2023-01-18 20:48 UTC, mbyrnepr2 commented
Done @DanielNoord: https://github.com/PyCQA/astroid/pull/1971. Let me know if any issues.

2023-01-18 20:49 UTC, DanielNoord commented
Thanks! I feel bad for asking, but could you do https://github.com/PyCQA/astroid/pull/1970 as well? :smile:

It's my own PR but I haven't been able to fix the broken `git remote` issue on my local machine.. :sweat_smile: