Turtle brain and unit test, fix PyCQA/astroid#849
PyCQA/astroid pull request #875
Opened 2020-12-31 19:51 UTC by rioj7

## Steps

- [ ] For new features or bug fixes, add a ChangeLog entry describing what your PR does.
- [x ] Write a good description on what the PR does.

## Description

Add a brain for the python Turtle module, and a unit test for this brain

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :sparkles: New feature |

## Related Issue

2021-02-16 13:45 UTC, hippo91 requested changes
@rioj7 thanks a lot for this PR.
It's almost goog, i just left a pair of comments.
By the way, the CI is failing because `black` thinks there is something to reformat.

2021-02-16 13:45 UTC, hippo91 commented on astroid/brain/brain_turtle.py
> +"""
It is interesting but i'm not sure it is the right place to store this script. Why not in a proper repo on your github account, with a link toward it?

2021-02-16 13:45 UTC, hippo91 commented on astroid/brain/brain_turtle.py
> +"""
In fact i'v got a similar script that i used for `numpy` but it doesn't make part of `astroid` sources.

2021-02-16 13:45 UTC, hippo91 commented on tests/unittest_brain_turtle.py
> +        self.assertEqual(inferred.name, 'pencolor')
Why just focusing on `pencolor` function?
It should be possible to loop over all the function you added in the brain and make for each of them the same tests you are doing here.

2021-02-16 13:45 UTC, hippo91 commented on tests/unittest_brain_turtle.py
> +        self.assertIsInstance(inferred, astroid.Instance)
If i understand well, you are not testing the brain you added but the classical `astroid` behavior (i.e not using the brain).
Am i correct?
If yes, i don't see the point.

2022-11-19 15:02 UTC, Pierre-Sassoulas commented
Closing as stale / abandoned. Feel free to open another MR if the issue still need addressing.

2022-11-19 15:02 UTC, closed without merging